<?php
require_once("backend/controllers/ProductController.php");

$controller = new ProductController();
$products = $controller->index();

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="node_modules/slick-carousel/slick/slick.css">
    <link rel="stylesheet" href="node_modules/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <title>Product List</title>
</head>
<body>

<div class="container px-3">
    <div class="row py-5 mx-5">
        <h3 class="col-6 justify-content-md-start">Product List</h3>
        <div class="col-6 d-grid gap-2 d-md-flex">
            <a class="btn btn-success" href="add-product.phtml">ADD</a>
            <button type="button" id="delete-product-btn" class="btn btn-success">MASS DELETE</button>
        </div>
        <p>
        <hr>
        <div class="slider multiple-items">
            <?php foreach ($products as $product) { ?>
                <div class="card">
                    <input class="form-check-input delete-checkbox" type="checkbox" value="<?= $product->getId() ?>">
                    <label class="form-check-label"></label>
                    <div class="card-body">
                        <?php foreach ($product->toIndexArray() as $field => $value) { ?>
                            <p><?= $value ?></p>
                        <?php } ?>
                    </div>
                </div>
            <?php } ?>
        </div>
        <p>
        <hr>
    </div>
</div>
<script src="node_modules/jquery/dist/jquery.min.js" type="text/javascript"></script>
<script src="node_modules/slick-carousel/slick/slick.min.js" type="text/javascript"></script>
<script src="node_modules/jquery-validation/dist/jquery.validate.min.js" type="text/javascript"></script>
<script src="script.js"></script>
</body>
</html>
